### ISSUE TITLE
Mark dataValue in CS-wronglock as volatile

### ISSUE THREAD

**Issue by kostis** [mc-imperial/sctbench#1]
Manually apply the pull request specified [here](https://github.com/sctbenchmarks/sctbenchmarks/pull/3) and investigate whether there are other cases like that in some benchmarks.

Also, add a note to the other repository that its repo has been moved to this one.

**Comment by paulthomson** [comment]
I have made the changes here. I have updated the old repo's README. I have added another issue for investigating. Thanks!
