### ISSUE TITLE
About copyright and license

### ISSUE THREAD

**Issue by fanhy2114** [mc-imperial/sctbench#3]
Hi, We made some adaptations based on your benchmarks and performed some experiments.  Now we want to contribute some benchmarks to the [SV-COMP](https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks). 

Since Copyright and License are required. I wonder to know if it is permitted to use and modify your benchmarks, or if your can provide me with your `copyright` and `License`.

**Comment by afd** [comment]
@paulthomson Would you be able to advise on this?

**Comment by fanhy2114** [comment]
Thanks for your reply. @paulthomson @afd. 

No matter what kind of copyright, we will definitely obtain your permission before using it.

Since the submission deadline is coming soon. I wonder if the following would be an acceptable way: we will explicitly declare that these benchmarks (we use four of your benchmarks: `arithmetic*, reorder*, circular`, and `Dining5`) with:
```
Copyright: 2016 The SCTBench project
```
And the license is the same as the Software Competition Community, will be the `Apache 2.0`

**Comment by paulthomson** [comment]
@fanhy2114 Sorry for the delay. I am happy to license my contributions (scripts, modifications, etc.) under Apache 2.0. However, I am not the author of any of the benchmarks; they are all from third parties. It sounds like the benchmarks you use are from `concurrent-software-benchmarks` and `inspect_examples`. 

You might be able to find the original authors and licenses via our paper:

https://www.doc.ic.ac.uk/~afd/homepages/papers/pdfs/2014/PPoPP.pdf

It sounds like `concurrent-software-benchmarks` might be from:

L. Cordeiro and B. Fischer. Verifying multi-threaded software
using SMT-based context-bounded model checking. In ICSE,
pages 331–340, 2011.

And `inspect_examples`:

Y. Yang, X. Chen, and G. Gopalakrishnan. Inspect: A runtime model checker for multithreaded C programs. Technical
Report UUCS-08-004, University of Utah, 2008.

**Comment by fanhy2114** [comment]
Thank you too much for your reply. That's really helpful.
